-- ALTER TABLE settings ADD COLUMNS (run in Supabase SQL Editor)

ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_title TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS hero_subtitle TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS locale TEXT DEFAULT 'en';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#C8A45C';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#B8933D';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#D4C9C0';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS dark_mode BOOLEAN DEFAULT true;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS font_heading TEXT DEFAULT 'Playfair Display';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS font_body TEXT DEFAULT 'Inter';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS footer_copyright TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS seo_title TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS og_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS story_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS about_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS featured_dish_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS featured_dish_1_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS featured_dish_2_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS featured_dish_3_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS featured_dish_4_image TEXT DEFAULT '';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS full_house_image TEXT DEFAULT '';
